version: "3"

services:
  api-nginx:
    container_name: api
    build:
      context: api/docker
      dockerfile: nginx/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "${DOCKER_API_PORT}:80"
    depends_on:
      - api-php-fpm
    restart: unless-stopped

  api-php-fpm:
    container_name: api.fpm
    build:
      context: api/docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DOCKER_DATABASE_USER}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_DB: ${DOCKER_DATABASE_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${DOCKER_DATABASE_PORT}:5432"